### ISSUE TITLE
Parent directory might not exists before exporting

### ISSUE THREAD

**Issue by uduse** [niftylab/laygo2_workspace_sky130#5]
```python
File /laygo2_workspace_sky130/laygo2_example/logic/inv.py:105
    102 print("")
    104 # Uncomment for BAG export
--> 105 laygo2.interface.magic.export(lib, filename=ref_dir_MAG_exported +libname+'_'+cellname+'.tcl', cellname=None, libpath=ref_dir_template+'magic_layout', scale=1, reset_library=False, tech_library='sky130A')
    106 # 8. Export to a template database file.
    107 nat_temp = dsn.export_to_template()

File /usr/local/lib/python3.8/dist-packages/laygo2/interface/magic.py:267, in export(db, filename, cellname, libpath, scale, reset_library, tech_library, gds_filename)
    264     cmd += "gds write "+gds_filename+"\n"
    266 if filename is not None:  # export to a file.
--> 267     with open(filename, "w") as f:
    268         f.write(cmd)
    270 return cmd

FileNotFoundError: [Errno 2] No such file or directory: './laygo2_example/logic/TCL/logic_generated_inv_2x.tcl'
```

I followed the example [here](https://laygo2-sky130-docs.readthedocs.io/en/main/run_example.html) and it reported this error because the parent directory `./laygo2_example/logic/TCL` doesn't exists. Two possible solutions here (1) create a parent directory by staging a stub file e.g., `TCL/.keep` so the directory always exists in the user's filesystem (2) dynamically create a directory if not exists in `magic.py`

Reference line:
https://github.com/niftylab/laygo2/blob/8973f1cea804f6ad71ff76f25cada29f31ff5b42/laygo2/interface/magic.py#L267

**Comment by jdhan** [comment]
Thanks for your suggestions. I added .keep files in TCL directories to retain the path hierarchy.
